# Generated by Django 2.2.4 on 2019-08-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipments',
            old_name='ShipmentId',
            new_name='shipmentId',
        ),
        migrations.RenameField(
            model_name='shipments',
            old_name='name',
            new_name='shipmentName',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='ShipmentStatus',
        ),
        migrations.AddField(
            model_name='shipments',
            name='shipmentStatus',
            field=models.BooleanField(default=True),
        ),
    ]
